package com.uzeyir.photoselector

internal object UiText {
    const val reviewSelection = "Seçimi İncele"
    const val confirmSelection = "Seçimi Onayla"
    const val folderTitle = "Fotoğraf Klasörünü Seç"
    const val selectFolder = "Klasör Seç"
    const val selected = "Seçilen"
    const val total = "Toplam"
    const val review = "İncele"
    const val back = "Geri"
    const val backToGallery = "Galeriye Dön"
    const val reviewLikedPhotos = "Seçilen Fotoğraflar"
    const val finalConfirmation = "Son Onay"
    const val selectedJpg = "Seçilen JPG"
    const val matchingRaw = "Eşleşen RAW"
    const val totalFiles = "Toplam dosya"
    const val copyJpgAndRaw = "JPG + RAW Kopyala"
    const val copyingSelectedFiles = "Seçilen dosyalar kopyalanıyor..."
    const val exportComplete = "Dışa aktarma tamamlandı"
    const val folder = "Klasör"
    const val copiedFiles = "Kopyalanan dosya"
    const val finish = "Bitir"
    const val exportFailed = "Dışa aktarma başarısız"
    const val retry = "Tekrar Dene"
    const val like = "Beğen"
    const val previousPhoto = "Önceki fotoğraf"
    const val nextPhoto = "Sonraki fotoğraf"
    const val noSourceFolder = "Kaynak klasör seçilmedi."
    const val noLikedPhotos = "Seçilen fotoğraf yok."
    const val selectAtLeastOnePhoto = "En az bir fotoğraf seçin."
    const val exportFailedFallback = "Dışa aktarma başarısız oldu."
    const val couldNotCreateExportFolder = "Dışa aktarma klasörü oluşturulamadı."
    const val couldNotOpenOutputStream = "Hedef dosya açılamadı."
    const val couldNotOpenInputStream = "Kaynak dosya açılamadı."
    const val checkUpdate = "Güncellemeyi Kontrol Et"
    const val checkingUpdate = "Kontrol ediliyor"
    const val appUpToDate = "Uygulama güncel"
    const val downloadingUpdate = "İndiriliyor"
    const val readyToInstall = "Kuruluma hazır"
    const val updateCheckFailed = "Güncelleme kontrol edilemedi"

    fun price(amount: Int): String = "$amount TL"
    fun selectedCount(count: Int): String = "$selected: $count"
    fun selectedJpgCount(count: Int): String = "$selectedJpg: $count"
    fun matchingRawCount(count: Int): String = "$matchingRaw: $count"
    fun totalFileCount(count: Int): String = "$totalFiles: $count"
    fun folderName(name: String): String = "$folder: $name"
    fun copiedFileCount(count: Int): String = "$copiedFiles: $count"
    fun couldNotCreateFile(name: String): String = "$name oluşturulamadı."
    fun updateAvailable(versionName: String): String = "Yeni sürüm var: $versionName"
}
