package com.uzeyir.photoselector

enum class AppLanguage {
    Turkish,
    English
}

enum class UiMessage {
    SelectAtLeastOnePhoto,
    SdCardNotInserted,
    SdCardPickerUnsupported,
    FolderLoadFailed,
    NoSourceFolder,
    NoLikedPhotos,
    ExportFailedFallback,
    CouldNotCreateExportFolder,
    CouldNotCreateFile,
    CouldNotOpenOutputStream,
    CouldNotOpenInputStream,
    CopyVerificationFailed
}

data class LocalizedStrings(
    val languageOptionTurkish: String,
    val languageOptionEnglish: String,
    val confirmSelection: String,
    val allPhotos: String,
    val favorites: String,
    val noFavoritesYet: String,
    val goToAllPhotos: String,
    val galleryTitle: String,
    val returnHome: String,
    val returnHomeWarningTitle: String,
    val returnHomeWarningMessage: String,
    val stayHere: String,
    val folderTitle: String,
    val selectFolder: String,
    val openSdCard: String,
    val chooseSdCard: String,
    val photo: String,
    val photoShort: String,
    val video: String,
    val videoShort: String,
    val priceBreakdown: String,
    val selected: String,
    val total: String,
    val yes: String,
    val no: String,
    val discount: String,
    val filesToCopy: String,
    val fileUnit: String,
    val copyProgress: String,
    val shareProgress: String,
    val review: String,
    val back: String,
    val finalConfirmation: String,
    val finalConfirmationSubtitle: String,
    val selectedJpg: String,
    val matchingRaw: String,
    val selectedVideo: String,
    val rawIncluded: String,
    val totalFiles: String,
    val copyJpgAndRaw: String,
    val copySelectedFiles: String,
    val includeRawFiles: String,
    val whatsAppDocumentShare: String,
    val whatsAppShareFailed: String,
    val returnToGallery: String,
    val exportComplete: String,
    val folder: String,
    val copiedFiles: String,
    val exportFailed: String,
    val retry: String,
    val secureProcessingNotice: String,
    val like: String,
    val rotate: String,
    val fullscreen: String,
    val exitFullscreen: String,
    val previousPhoto: String,
    val nextPhoto: String,
    val adminPanel: String,
    val adminPassword: String,
    val adminPricing: String,
    val adminThemes: String,
    val adminSdCardFolder: String,
    val adminPreferredSdCardFolder: String,
    val adminPreferredSdCardFolderDescription: String,
    val adminChooseSdCardFolder: String,
    val adminClearSdCardFolder: String,
    val adminNoSdCardFolderSelected: String,
    val adminSdCardFolderSaved: String,
    val adminSdCardFolderCleared: String,
    val adminLogin: String,
    val adminPasswordChange: String,
    val adminCurrentPassword: String,
    val adminNewPassword: String,
    val adminRepeatNewPassword: String,
    val adminChange: String,
    val adminPhotoPrice: String,
    val adminVideoPrice: String,
    val adminLimitCount: String,
    val adminDiscountTiers: String,
    val adminTierItemCount: String,
    val adminTierPercent: String,
    val adminDelete: String,
    val adminAddTier: String,
    val adminSave: String,
    val adminResetDefaults: String,
    val adminPasswordMinError: String,
    val adminPasswordWrong: String,
    val adminPasswordChanged: String,
    val adminPasswordChangeFailed: String,
    val adminPricingSaved: String,
    val adminPricingInvalid: String,
    val adminPricingReset: String,
    val themeSignatureGold: String,
    val themeSignatureGoldDescription: String,
    val themeRedBlackWhite: String,
    val themeRedBlackWhiteDescription: String,
    val themeGraphiteCopper: String,
    val themeGraphiteCopperDescription: String,
    val themeMidnightRose: String,
    val themeMidnightRoseDescription: String,
    val checkUpdate: String,
    val checkingUpdate: String,
    val appUpToDate: String,
    val downloadingUpdate: String,
    val readyToInstall: String,
    val updateCheckFailed: String,
    private val updateAvailableText: (String) -> String,
    private val selectAtLeastOnePhoto: String,
    private val sdCardNotInserted: String,
    private val sdCardPickerUnsupported: String,
    private val folderLoadFailed: String,
    private val noSourceFolder: String,
    private val noLikedPhotos: String,
    private val exportFailedFallback: String,
    private val couldNotCreateExportFolder: String,
    private val couldNotOpenOutputStream: String,
    private val couldNotOpenInputStream: String,
    private val couldNotCreateFile: (String) -> String,
    private val copyVerificationFailed: (String) -> String
) {
    fun price(amount: Int): String = "$amount TL"
    fun selectedCount(count: Int): String = "$selected: $count"
    fun selectedJpgCount(count: Int): String = "$selectedJpg: $count"
    fun matchingRawCount(count: Int): String = "$matchingRaw: $count"
    fun selectedVideoCount(count: Int): String = "$selectedVideo: $count"
    fun totalFileCount(count: Int): String = "$totalFiles: $count"
    fun filesToCopyCount(count: Int): String = "$filesToCopy: $count $fileUnit"
    fun yesNo(value: Boolean): String = if (value) yes else no
    fun folderName(name: String): String = "$folder: $name"
    fun copiedFileCount(count: Int): String = "$copiedFiles: $count"
    fun updateAvailable(versionName: String): String = updateAvailableText(versionName)

    fun message(message: UiMessage, argument: String? = null): String = when (message) {
        UiMessage.SelectAtLeastOnePhoto -> selectAtLeastOnePhoto
        UiMessage.SdCardNotInserted -> sdCardNotInserted
        UiMessage.SdCardPickerUnsupported -> sdCardPickerUnsupported
        UiMessage.FolderLoadFailed -> folderLoadFailed
        UiMessage.NoSourceFolder -> noSourceFolder
        UiMessage.NoLikedPhotos -> noLikedPhotos
        UiMessage.ExportFailedFallback -> exportFailedFallback
        UiMessage.CouldNotCreateExportFolder -> couldNotCreateExportFolder
        UiMessage.CouldNotOpenOutputStream -> couldNotOpenOutputStream
        UiMessage.CouldNotOpenInputStream -> couldNotOpenInputStream
        UiMessage.CouldNotCreateFile -> couldNotCreateFile(argument.orEmpty())
        UiMessage.CopyVerificationFailed -> copyVerificationFailed(argument.orEmpty())
    }
}

fun AppUpdateStatus.label(strings: LocalizedStrings): String = when (this) {
    AppUpdateStatus.Idle -> strings.checkUpdate
    AppUpdateStatus.Checking -> strings.checkingUpdate
    AppUpdateStatus.UpToDate -> strings.appUpToDate
    is AppUpdateStatus.Available -> strings.updateAvailable(versionName)
    AppUpdateStatus.Downloading -> strings.downloadingUpdate
    AppUpdateStatus.ReadyToInstall -> strings.readyToInstall
    AppUpdateStatus.Error -> strings.updateCheckFailed
}

internal object UiText {
    val defaultLanguage = AppLanguage.Turkish

    internal val turkish = LocalizedStrings(
        languageOptionTurkish = "Türkçe",
        languageOptionEnglish = "English",
        confirmSelection = "Onayla",
        allPhotos = "Tüm Fotoğraflar",
        favorites = "Favorilerim",
        noFavoritesYet = "Henüz favori seçilmedi.",
        goToAllPhotos = "Tüm Fotoğraflara Git",
        galleryTitle = "Galeri",
        returnHome = "Ana sayfaya dön",
        returnHomeWarningTitle = "Ana sayfaya dönülsün mü?",
        returnHomeWarningMessage = "Ana sayfaya dönerseniz bu klasörde yaptığınız seçimler ve işlem durumu silinir.",
        stayHere = "Vazgeç",
        folderTitle = "Fotoğraf Klasörünü Seç",
        selectFolder = "Klasör Seç",
        openSdCard = "SD Kartı Aç",
        chooseSdCard = "SD Kart Seç",
        photo = "Fotoğraf",
        photoShort = "Foto",
        video = "Video",
        videoShort = "Video",
        priceBreakdown = "Fiyat",
        selected = "Seçilen",
        total = "Toplam",
        yes = "Evet",
        no = "Hayır",
        discount = "İndirim",
        filesToCopy = "Kopyalanacak",
        fileUnit = "dosya",
        copyProgress = "Kopyalama ilerlemesi",
        shareProgress = "Paylaşıma hazırlanıyor",
        review = "İncele",
        back = "Geri",
        finalConfirmation = "Son Onay",
        finalConfirmationSubtitle = "Seçilen dosyaları kontrol edin ve işlemi başlatın.",
        selectedJpg = "Seçilen JPG",
        matchingRaw = "Eşleşen RAW",
        selectedVideo = "Seçilen video",
        rawIncluded = "RAW dahil",
        totalFiles = "Toplam dosya",
        copyJpgAndRaw = "JPG + RAW Kopyala",
        copySelectedFiles = "Seçilenleri Kopyala",
        includeRawFiles = "RAW dosyalarını dahil et",
        whatsAppDocumentShare = "WhatsApp belge olarak gönder",
        whatsAppShareFailed = "WhatsApp açılamadı.",
        returnToGallery = "Galeriye dön",
        exportComplete = "Dışa aktarma tamamlandı",
        folder = "Klasör",
        copiedFiles = "Kopyalanan dosya",
        exportFailed = "Dışa aktarma başarısız",
        retry = "Tekrar Dene",
        secureProcessingNotice = "Dosyalarınız güvenli şekilde işlenecektir.",
        like = "Beğen",
        rotate = "Döndür",
        fullscreen = "Tam ekran",
        exitFullscreen = "Tam ekrandan çık",
        previousPhoto = "Önceki fotoğraf",
        nextPhoto = "Sonraki fotoğraf",
        adminPanel = "Admin panel",
        adminPassword = "Şifre",
        adminPricing = "Fiyatlar",
        adminThemes = "Tema",
        adminSdCardFolder = "SD kart",
        adminPreferredSdCardFolder = "Varsayılan SD kart klasörü",
        adminPreferredSdCardFolderDescription = "Bu klasör seçilirse ana ekrandaki SD Kartı Aç butonu izin istemeden doğrudan burayı açar.",
        adminChooseSdCardFolder = "Klasör seç",
        adminClearSdCardFolder = "Klasörü temizle",
        adminNoSdCardFolderSelected = "Varsayılan klasör seçilmedi.",
        adminSdCardFolderSaved = "SD kart klasörü kaydedildi.",
        adminSdCardFolderCleared = "SD kart klasörü temizlendi.",
        adminLogin = "Giriş",
        adminPasswordChange = "Şifre değiştir",
        adminCurrentPassword = "Eski şifre",
        adminNewPassword = "Yeni şifre",
        adminRepeatNewPassword = "Yeni şifre tekrar",
        adminChange = "Değiştir",
        adminPhotoPrice = "Foto fiyatı",
        adminVideoPrice = "Video fiyatı",
        adminLimitCount = "Limit adedi",
        adminDiscountTiers = "İndirim basamakları",
        adminTierItemCount = "Adet",
        adminTierPercent = "Yüzde",
        adminDelete = "Sil",
        adminAddTier = "Basamak ekle",
        adminSave = "Kaydet",
        adminResetDefaults = "Varsayılana dön",
        adminPasswordMinError = "Şifre en az 4 haneli olmalı.",
        adminPasswordWrong = "Şifre hatalı.",
        adminPasswordChanged = "Şifre değiştirildi.",
        adminPasswordChangeFailed = "Eski şifre, yeni şifre veya tekrar alanı hatalı.",
        adminPricingSaved = "Fiyatlar kaydedildi.",
        adminPricingInvalid = "Fiyat değerlerini kontrol edin.",
        adminPricingReset = "Varsayılan fiyatlara dönüldü.",
        themeSignatureGold = "Mat altın",
        themeSignatureGoldDescription = "Ana sayfa örneğindeki koyu mat yüzey ve altın aksan.",
        themeRedBlackWhite = "Koyu kırmızı / siyah / beyaz",
        themeRedBlackWhiteDescription = "Koyu siyah yüzey, kırmızı aksan ve beyaz tipografi.",
        themeGraphiteCopper = "Grafit bakır",
        themeGraphiteCopperDescription = "Koyu grafit yüzeyler, bakır vurgu ve sıcak gri metin.",
        themeMidnightRose = "Gece rose",
        themeMidnightRoseDescription = "Gece tonu koyu yüzey, rose vurgu ve yumuşak açık metin.",
        checkUpdate = "Güncellemeyi Kontrol Et",
        checkingUpdate = "Kontrol ediliyor",
        appUpToDate = "Uygulama güncel",
        downloadingUpdate = "İndiriliyor",
        readyToInstall = "Kuruluma hazır",
        updateCheckFailed = "Güncelleme kontrol edilemedi",
        updateAvailableText = { versionName -> "Yeni sürüm var: $versionName" },
        selectAtLeastOnePhoto = "En az bir fotoğraf seçin.",
        sdCardNotInserted = "SD kart takılı değil.",
        sdCardPickerUnsupported = "Bu Android sürümünde SD kart doğrudan açılamıyor. Lütfen Klasör Seç ile devam edin.",
        folderLoadFailed = "Klasör açılamadı. Lütfen izinleri kontrol edip tekrar seçin.",
        noSourceFolder = "Kaynak klasör seçilmedi.",
        noLikedPhotos = "Seçilen fotoğraf yok.",
        exportFailedFallback = "Dışa aktarma başarısız oldu.",
        couldNotCreateExportFolder = "Dışa aktarma klasörü oluşturulamadı.",
        couldNotOpenOutputStream = "Hedef dosya açılamadı.",
        couldNotOpenInputStream = "Kaynak dosya açılamadı.",
        couldNotCreateFile = { name -> "$name oluşturulamadı." },
        copyVerificationFailed = { name -> "$name doğru kopyalanamadı. Lütfen SD kart izinlerini kontrol edip tekrar deneyin." }
    )

    internal val english = LocalizedStrings(
        languageOptionTurkish = "Türkçe",
        languageOptionEnglish = "English",
        confirmSelection = "Confirm",
        allPhotos = "All Photos",
        favorites = "Favorites",
        noFavoritesYet = "No favorites selected yet.",
        goToAllPhotos = "Go to All Photos",
        galleryTitle = "Gallery",
        returnHome = "Return home",
        returnHomeWarningTitle = "Return to the start screen?",
        returnHomeWarningMessage = "If you return home, selections and progress for this folder will be cleared.",
        stayHere = "Cancel",
        folderTitle = "Select Photo Folder",
        selectFolder = "Select Folder",
        openSdCard = "Open SD Card",
        chooseSdCard = "Choose SD Card",
        photo = "Photo",
        photoShort = "Photo",
        video = "Video",
        videoShort = "Video",
        priceBreakdown = "Price",
        selected = "Selected",
        total = "Total",
        yes = "Yes",
        no = "No",
        discount = "Discount",
        filesToCopy = "To copy",
        fileUnit = "files",
        copyProgress = "Copy progress",
        shareProgress = "Preparing share",
        review = "Review",
        back = "Back",
        finalConfirmation = "Final Confirmation",
        finalConfirmationSubtitle = "Review the selected files and start the process.",
        selectedJpg = "Selected JPG",
        matchingRaw = "Matching RAW",
        selectedVideo = "Selected video",
        rawIncluded = "RAW included",
        totalFiles = "Total files",
        copyJpgAndRaw = "Copy JPG + RAW",
        copySelectedFiles = "Copy selected files",
        includeRawFiles = "Include RAW files",
        whatsAppDocumentShare = "Send as WhatsApp document",
        whatsAppShareFailed = "Could not open WhatsApp.",
        returnToGallery = "Return to gallery",
        exportComplete = "Export complete",
        folder = "Folder",
        copiedFiles = "Copied files",
        exportFailed = "Export failed",
        retry = "Retry",
        secureProcessingNotice = "Your files will be processed securely.",
        like = "Like",
        rotate = "Rotate",
        fullscreen = "Fullscreen",
        exitFullscreen = "Exit fullscreen",
        previousPhoto = "Previous photo",
        nextPhoto = "Next photo",
        adminPanel = "Admin panel",
        adminPassword = "Password",
        adminPricing = "Pricing",
        adminThemes = "Theme",
        adminSdCardFolder = "SD card",
        adminPreferredSdCardFolder = "Default SD card folder",
        adminPreferredSdCardFolderDescription = "When this folder is selected, the home screen SD Card button opens it directly without asking again.",
        adminChooseSdCardFolder = "Choose folder",
        adminClearSdCardFolder = "Clear folder",
        adminNoSdCardFolderSelected = "No default folder selected.",
        adminSdCardFolderSaved = "SD card folder saved.",
        adminSdCardFolderCleared = "SD card folder cleared.",
        adminLogin = "Log in",
        adminPasswordChange = "Change password",
        adminCurrentPassword = "Current password",
        adminNewPassword = "New password",
        adminRepeatNewPassword = "Repeat new password",
        adminChange = "Change",
        adminPhotoPrice = "Photo price",
        adminVideoPrice = "Video price",
        adminLimitCount = "Limit count",
        adminDiscountTiers = "Discount tiers",
        adminTierItemCount = "Count",
        adminTierPercent = "Percent",
        adminDelete = "Delete",
        adminAddTier = "Add tier",
        adminSave = "Save",
        adminResetDefaults = "Reset defaults",
        adminPasswordMinError = "Password must be at least 4 digits.",
        adminPasswordWrong = "Incorrect password.",
        adminPasswordChanged = "Password changed.",
        adminPasswordChangeFailed = "Current password, new password, or repeat field is invalid.",
        adminPricingSaved = "Pricing saved.",
        adminPricingInvalid = "Check the pricing values.",
        adminPricingReset = "Default pricing restored.",
        themeSignatureGold = "Matte gold",
        themeSignatureGoldDescription = "Dark matte surface and gold accent from the home screen sample.",
        themeRedBlackWhite = "Dark red / black / white",
        themeRedBlackWhiteDescription = "Dark black surface, red accent, and white typography.",
        themeGraphiteCopper = "Graphite copper",
        themeGraphiteCopperDescription = "Dark graphite surfaces, copper accent, and warm gray text.",
        themeMidnightRose = "Midnight rose",
        themeMidnightRoseDescription = "Midnight dark surface, rose accent, and soft light text.",
        checkUpdate = "Check for Updates",
        checkingUpdate = "Checking",
        appUpToDate = "App is up to date",
        downloadingUpdate = "Downloading",
        readyToInstall = "Ready to install",
        updateCheckFailed = "Update check failed",
        updateAvailableText = { versionName -> "New version available: $versionName" },
        selectAtLeastOnePhoto = "Select at least one photo.",
        sdCardNotInserted = "SD card is not inserted.",
        sdCardPickerUnsupported = "This Android version cannot open the SD card directly. Please use Select Folder.",
        folderLoadFailed = "Could not open the folder. Please check permissions and select it again.",
        noSourceFolder = "Source folder was not selected.",
        noLikedPhotos = "No selected photos.",
        exportFailedFallback = "Export failed.",
        couldNotCreateExportFolder = "Could not create export folder.",
        couldNotOpenOutputStream = "Could not open destination file.",
        couldNotOpenInputStream = "Could not open source file.",
        couldNotCreateFile = { name -> "$name could not be created." },
        copyVerificationFailed = { name -> "$name was not copied correctly. Please check SD card permissions and try again." }
    )

    fun strings(language: AppLanguage): LocalizedStrings = when (language) {
        AppLanguage.Turkish -> turkish
        AppLanguage.English -> english
    }
}
